### ISSUE TITLE
Test failures on mono 4.4

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-dotnet-client#171]
There are several tests that fail on mono 4.4 but pass on mono 4.2 with an exception similar to the one below:

```
32) Test Error : RabbitMQ.Client.Unit.TestConnectionRecovery.TestUnblockedListenersRecovery
   System.ArgumentException : The IPEndPoint was created using InterNetwork AddressFamily but SocketAddress contains InterNetworkV6 instead, please use the same type.
  at System.Net.IPEndPoint.Create (System.Net.SocketAddress socketAddress) <0x2eb7410 + 0x0051b> in <filename unknown>:0
  at System.Net.Sockets.Socket.get_LocalEndPoint () <0x2eb7240 + 0x0005f> in <filename unknown>:0
  at RabbitMQ.Client.Impl.SocketFrameHandler.get_LocalEndPoint () <0x2eb7208 + 0x00023> in <filename unknown>:0
  at RabbitMQ.Client.Impl.SocketFrameHandler.get_LocalPort () <0x2eb71b0 + 0x00013> in <filename unknown>:0
  at RabbitMQ.Client.Framing.Impl.Connection.get_LocalPort () <0x2eb7190 + 0x00018> in <filename unknown>:0
  at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.get_LocalPort () <0x2eb7168 + 0x00017> in <filename unknown>:0
  at RabbitMQ.Client.Unit.IntegrationFixture+<CloseConnection>c__AnonStorey8.<>m__0 (RabbitMQ.Client.Unit.ConnectionInfo x) <0x2eb7100 + 0x00018> in <filename unknown>:0
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x2eb6ee0 + 0x0007c> in <filename unknown>:0
  at RabbitMQ.Client.Unit.IntegrationFixture.CloseConnection (IConnection conn) <0x2e95790 + 0x000df> in <filename unknown>:0
  at RabbitMQ.Client.Unit.TestConnectionRecovery.CloseAndWaitForRecovery (RabbitMQ.Client.Framing.Impl.AutorecoveringConnection conn) <0x2e95350 + 0x00043> in <filename unknown>:0
  at RabbitMQ.Client.Unit.TestConnectionRecovery.CloseAndWaitForRecovery () <0x2e952f0 + 0x00037> in <filename unknown>:0
  at RabbitMQ.Client.Unit.TestConnectionRecovery.TestUnblockedListenersRecovery () <0x31902d0 + 0x0010b> in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) 
```

**Comment by mattzink** [comment]
I _think_ that issue is a Mono bug, fixed in Mono 4.4.1

**Comment by michaelklishin** [comment]
Homebrew now provisions `4.4.1`, should be easy enough to try.

**Comment by kjnilsson** [comment]
It is still happening on 4.4.1. Given this is the current release this may need addressing/working around in the RabbitMQ client code. @mattzink have you got a link to Xamarins bugtracker for the issue you thought it was?

**Comment by kjnilsson** [comment]
The same tests pass when running the test suite on master using mono  (`dotnet run -f net451`) so it should be fixable by backporting some of the changes.

**Comment by kjnilsson** [comment]
I managed to create a small repro. Filed issue here: https://bugzilla.xamarin.com/show_bug.cgi?id=42738

**Comment by mattzink** [comment]
@kjnilsson I thought you were maybe running into the issue described here:
https://github.com/mono/mono/commit/587a89e17c038521eaf52866d25affadc52db4ff

But perhaps you are hitting https://github.com/mono/mono/pull/3237 which was just committed to the Mono 4.4 branch but not yet in any release

**Comment by kjnilsson** [comment]
The PR for the workaround is merged and the tests now pass on mono 4.4.1. Closing this issue.
